appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 0MBXmRDox0a3MqgpXOhtruPIZ4DHzU6zGdGN89ajETnwsQw2CfDV3sZouX64V5OVe6yXFJAHW/EbXVK2xw6d3M8ziOBAdh3e/G5kM3qEoNwjix6W8CsBaGeh7RpcyUEtlbkFg0PAQbdtjUpJah5KWuo7jZ4pdXEYXTuNKni8SVMUdfuK50K0OEBTiXzQrN+khRPbAoIm9Gvgj8/JJdXM9oobTzsKiDjxC5Ir33b33lz+e3eeVC6/3T+Lwa74T3VnrVujK/8JZuuAhLtI1Cj5A+s5mDdT/5vrjGBA9JWYEqonTTjcAvJMlcELmuk8CZRS1iMburcvqJxbDn3Pipb2D6tQVQED5vvn+tfheXwgCu3t/FTxH1F4keLgzaMq+3MO18+LRCoZedbbRnZi26FNHgZC9CsyuFlOk3P6MoJo5zsPNiWjxycV8uDYETnh0mtzDnJ3Geqbdf8KBDcAdo5/JLgHblTAsQp5ZSorI7V2cAgdDDcCMg+qHx9msXOuS8jriOlFWLET6CHwlNh+7hEMNZyEQesCi8GwfzO7n+gMgPuZC9YG4MLbSVo6nVgGcFzYRfz4EQ7dQCSFeI0aaj3pVhj5td0va3XW40l2OFs8hzr2DeZMHyLZQn5BjoZHKilYJBAgfb75Q56GF2uAQGfDUugU8BK5HEmZUaJzlgT2TFo=
conda_forge_output_validation: true
